---
- name: Update web servers
  hosts: all
  remote_user: root

  tasks:
  - name: abc
    ansible.builtin.find:
      paths: /var/log
      patterns: '*'
      recurse: yes
      contents: 'asd'
    register: found_files

  - name: print files
    ansible.builtin.debug:
      var: found_files
