/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.K1kaGB.i __constants.c
/usr/bin/clang  -o __constants_data.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __constants_data.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.Ha9OJd.i __loader.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.xraOLr.i __helpers.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o __constants.o __constants.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o __loader.o __loader.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.4DI7ZS.i module.__main__.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o __helpers.o __helpers.c
/usr/bin/clang  -o __constants.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __constants.c
/usr/bin/clang  -o __loader.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __loader.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o module.__main__.o module.__main__.c
/usr/bin/clang  -o __helpers.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __helpers.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.zCqyFy.i static_src/MainProgram.c
/usr/bin/clang  -o module.__main__.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src module.__main__.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o static_src/MainProgram.o static_src/MainProgram.c
/usr/bin/clang  -o static_src/MainProgram.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src static_src/MainProgram.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.N9rJOD.i static_src/CompiledFunctionType.c
/usr/bin/clang  -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o static_src/CompiledFunctionType.o static_src/CompiledFunctionType.c
/usr/bin/clang  -o static_src/CompiledFunctionType.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src static_src/CompiledFunctionType.c
/usr/bin/clang  -o /home/afeser/Automated-Software-Testing-Project/sym/a/deneme.bin -z noexecstack -Wl,-R,/usr/lib -Wl,--disable-new-dtags @./@link_input.txt -L/usr/lib -ldl -lm -lpython3.11
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.GKc47L.i __constants.c
/usr/bin/clang -emit-llvm -o __constants_data.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __constants_data.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.WBgY6F.i __loader.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.rg0LQj.i __helpers.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o __constants.o __constants.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o __loader.o __loader.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o __helpers.o __helpers.c
/usr/bin/clang -emit-llvm -o __constants.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __constants.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.mxyqOv.i module.__main__.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o module.__main__.o module.__main__.c
/usr/bin/clang -emit-llvm -o __helpers.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __helpers.c
/usr/bin/clang -emit-llvm -o __loader.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src __loader.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.8nSXtZ.i static_src/MainProgram.c
/usr/bin/clang -emit-llvm -o module.__main__.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src module.__main__.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o static_src/MainProgram.o static_src/MainProgram.c
/usr/bin/clang -emit-llvm -o static_src/MainProgram.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src static_src/MainProgram.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -E -o /run/user/1000/ccache-tmp/cpp_stdout.tmp.PIWmEQ.i static_src/CompiledFunctionType.c
/usr/bin/clang -emit-llvm -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src -c -o static_src/CompiledFunctionType.o static_src/CompiledFunctionType.c
/usr/bin/clang -emit-llvm -o static_src/CompiledFunctionType.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.11 -I. -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/afeser/.local/lib/python3.11/site-packages/nuitka/build/static_src static_src/CompiledFunctionType.c
/usr/bin/clang -emit-llvm -o /home/afeser/Automated-Software-Testing-Project/sym/a/deneme.bin -z noexecstack -Wl,-R,/usr/lib -Wl,--disable-new-dtags @./@link_input.txt -L/usr/lib -ldl -lm -lpython3.11
