---
- name: Hostname test
  hosts: all
  remote_user: root

  tasks:
  # - name: Install apache httpd  (state=present is optional)
  #   ansible.builtin.apt:
  #     name: vim
  #     state: present # install apache2

  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: vim
      state: absent

